FROM python:latest

ENV DB_USER='e-commerce'
ENV DB_PASS='P6gbkQPwUZGbGazB'

ADD filter.py .

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

EXPOSE 8080 8080

CMD [ "python", "./filter.py", "flask"]